c4dt/showcase

- views/project.tpl
> Project view: Add link to docs if existing

- showcase.py
> Redirect /labs and /projects

- views/projects.tpl
> Set focus on search input

- data/DEDIS/projects.yaml
> DEDIS/protobuf: add maturity

- data/SPRING/projects.yaml
Score of 2/3, that looks good.
> SPRING/zksk: add maturity

- data/HexHive/projects.yaml
Taken from http://hexhive.epfl.ch/publications/, which is also the list of papers; while at it, I added the paper to some missing it.
> Adding/updating some HexHive projects.

- data/DEDIS/projects.yaml
- data/IVRL/projects.yaml
- data/LARA/projects.yaml
- data/LTS4/projects.yaml
- resources/styles.css
- showcase.py
- views/project.tpl
- views/projects.tpl
> Activity improvements

- showcase.py
- views/project.tpl
- views/projects.tpl
> Add tooltip for maturity level "moon" images

- .travis.yml
- requirements.txt
- update.sh
To be merged only **after** traefik is deployed on c4dtsrv1.
> Recreate the Python virtual env using the docker image

- Makefile
- data.py
- data/DEDIS/projects.yaml
- data/DSLAB/projects.yaml
- data/HexHive/projects.yaml
- data/IVRL/projects.yaml
- data/LCA2/projects.yaml
- data/LDS/projects.yaml
- requirements-test.txt
- requirements.txt
- showcase.py
- views/project.tpl
- views/projects.tpl
> Use strictyaml with schema

- data/MLO/projects.yaml
> Update mlBench layman desc

- data/MLO/projects.yaml
> Add mlbench to incubator

- data/MLO/projects.yaml
> Add MLBench blog and tutorials

- data/LDS/projects.yaml
> LDS/SPINDLE: initial

- data/LTS4/projects.yaml
foolbox is not a project from LTS4, so remove it
> remove foolbox

- data/LDS/projects.yaml
We released Lattigo v2.0.0 and would like to update the description on showcase.c4dt.org.
> Updated Lattigo description

- README.md
- data/template.yaml
Also adding a template for easy copy/pasing for new projects.
> Updating list of parameters in yaml

- data/LDS/projects.yaml
Forgot to add it to the demo list.
> LDS/spindle: add demo

- views/projects.tpl
> Add column with last activity, include in sort

- data.py
- data/DEDIS/projects.yaml
- data/LDS/projects.yaml
- views/info_item.tpl
- views/project.tpl
> Add optional "notes" data for information items

- data.py
- data/DEDIS/projects.yaml
- data/HexHive/projects.yaml
- data/LARA/projects.yaml
- data/LDS/projects.yaml
- data/MLO/projects.yaml
- data/SPRING/projects.yaml
- test_app.py
- views/project.tpl
> Add factory work field

- views/projects.tpl
> Use prof as default contact

- data/labs.yaml
- test_app.py
- views/labs.tpl
- views/project.tpl
- views/projects.tpl
> Rework lab visual info

- resources/styles.css
- views/projects.tpl
> Move title to top

- resources/maturity_na.svg
- showcase.py
> Add "N/A" for no maturity and improve tooltip

- data/DSLAB/projects.yaml
- data/NAL/projects.yaml
- updates/2021-02.md
Just in case you want to see the updates...
> DSLAB: added conference references

- data/DSLAB/projects.yaml
Fix for https://github.com/c4dt/showcase/pull/140#discussion_r584864853
> DSLAB: Fix for Cloud 9 paper

- data/MLO/projects.yaml
- updates/2021-02.md
This will collide with #145 - so please start merging with #145, then I'll update this one. Thanks!
> Add PowerGossip to MLO

- resources/styles.css
- views/breadcrumbs.tpl
- views/labs.tpl
- views/project.tpl
- views/projects.tpl
This implements the first "branch" as described in https://github.com/c4dt/TODO/issues/212#issuecomment-787940589.
> Add breadcrumb trail

- data.py
- data/LARA/projects.yaml
To be used in the incubator project pages.
> Add optional description to demos

- data/LARA/projects.yaml
- updates/2021-incremental-update-1.md
> LARA: update

- views/incubator/spindle.tpl
First draft of the spindle template, without image (next PR will do that).
> views/incubator/spindle: initial

- resources/incubator/images/spindle/network.svg
- views/incubator/spindle.tpl
Quite a simple figure, but does the trick of explaining the behavior of spindle (explained in text).
> spindle: add img

- data/DEDIS/projects.yaml
- updates/2021-incremental-update-1.md
By request of Pierluca, updates to the DEDIS repo.
> Updates to DEDIS

- data/LSIR/projects.yaml
- updates/2021-incremental-update-1.md
> LSIR: update

- data/DEDIS/projects.yaml
> DEDIS: Add maturity level for Calypso

- data/DEDIS/projects.yaml
> DEDIS/kyber: add maturity

- resources/styles.css
As discussed, this PR will simply switch the font family to Verdana.
> Changes the font-family to verdana sans serif

- views/labs.tpl
Same as on the "projects" page.
> Set default focus on Labs page to search field

- resources/styles.css
Fixes the tables that remained light in the dark mode
> Fixes tables dark mode

- data/MMSPG/projects.yaml
- updates/2021-incremental-update-1.md
As per https://github.com/c4dt/showcase/issues/136
> MMSPG: update

- data/DSLAB/projects.yaml
- data/NAL/projects.yaml
- updates/2021-incremental-update-1.md
> NAL: Update projects data

- data/DCL/projects.yaml
- views/incubator/at2.tpl
> DCL/AT2: add presentation

- data/DCL/projects.yaml
- requirements.txt
- views/incubator/at2.tpl
Holding onto the previous version of `ruamel.yaml` until it gets fixed
> Fix dependencies

- data.py
- data/LARA/projects.yaml
- data/LDS/projects.yaml
- test_app.py
- views/incubator/index.tpl
- views/incubator/project_base.tpl
- views/project.tpl
- Some clean-ups regarding demo URLs
- Display demonstrator info in project presentation if available (closes #194)
> Cleanup + use demo url in incubator

- data/DCL/projects.yaml
- resources/incubator/images/garfield/models.svg
- views/incubator/garfield.tpl
> Add Garfield presentation and demo info

- data/SPRING/projects.yaml
- updates/2021-incremental-update-1.md
> SPRING: Update projects data

- data.py
- data/DCL/projects.yaml
- data/DEDIS/projects.yaml
- data/DSLAB/projects.yaml
- data/HexHive/projects.yaml
- data/INDY/projects.yaml
- data/IVRL/projects.yaml
- data/LARA/projects.yaml
- data/LCA2/projects.yaml
- data/LDS/projects.yaml
- data/LSIR/projects.yaml
- data/LTS4/projects.yaml
- data/MLO/projects.yaml
- data/MMSPG/projects.yaml
- data/NAL/projects.yaml
- data/PARSA/projects.yaml
- data/SPRING/projects.yaml
- data/SalatheLab/projects.yaml
- showcase.py
- views/projects.tpl
Instead of adding one `colspan` line per category, this adds a category column.
Closes #207 
Closes #209
> Adding a new column for the categories

- resources/table.css
- views/projects.tpl
> Fix search edge-cases

- views/projects.tpl
Avoid using JSON encoded params and use more classical way to query for data. It also avoid serializing empty values as to not bloat the URL too much.
Closes: #229
> projects: use query string

- views/projects.tpl
> projects: fix reset

- data/LSIR/projects.yaml
> Remove outdated site

- data/DCL/projects.yaml
Add relevant papers covering the theory researched at DCL, of which Garfield is a practical application.
> Add relevant papers for Garfield

- data/DCL/projects.yaml
- data/ESL/projects.yaml
- data/IVRL/projects.yaml
- data/MLO/projects.yaml
* add DCL/carbon
* fix some typo I found while reading the showcase
> Add carbon

- data/LARA/projects.yaml
Maturity achieved 2, adding it to showcase
> LARA/rust-stainless: add maturity

- data/DSLAB/projects.yaml
- data/HexHive/projects.yaml
- data/IVRL/projects.yaml
- data/LIONS/projects.yaml
- data/RS3LAB/projects.yaml
- data/SPRING/projects.yaml
- data/SalatheLab/projects.yaml
Update the showcase with the latest evaluations for the second half of 2022.
> Adding latest maturity evaluations

- README.md
- views/projects.tpl
Sort labs, pillars and verticals dropdowns
fixes: #271
> Sort dropdowns

- data/MMSPG/projects.yaml
> add procam project

- views/projects.tpl
> fix bug where extra columns aren't hidden

- views/products/presentation/klint.tpl
small prez, will probably get updated along the way.
> DSLAB/klint: add prez

- .github/workflows/main.yml
we now deploy w/ ansible, no need for the github action anymore
OR review
> github: rm deploy

- data/SPRING/projects.yaml
> Update tandem/monero paper link

- data/MLO/projects.yaml
Adds the maturity evaluation level 2 for the powerSGD project
> data: upgrades PowerSGD maturity evaluation

- .gitignore
- data/LARA/projects.yaml
- data/LDS/projects.yaml
- views/products/demo/drynx.tpl
- views/products/demo/spindle.tpl
- views/products/demo/stainless-for-smart-contracts.tpl
update drynx, stainless, and spindle demo page to point to the archived git.
> archive old demos

- data/DEDIS/projects.yaml
- data/RS3LAB/projects.yaml
For Hydra, I found a link for the git repo, I added it, and also a link to the conference the paper was published in. Please validate and confirm the correctness of the data.
Additional question:   
Should I remove "Noémien Kocher" as contact from other projects he's in, or only HBT as suggested in the ticket? 
partially closes https://github.com/c4dt/showcase/issues/294 (check the last point in the ticket to avoid undesired automatic closure to the ticket.
> various data updates (for Hydra and HBT projects)

- README.md
- data.py
- data/DSLAB/projects.yaml
This PR also adds a new possible value for incubator/products/type: OSS-participation
Comes from c4dt/TODO#340
> Adding OSS work to klint

- data/DEDIS/projects.yaml
Passes Level: 1 -> Level: 2
[Maturity Evaluation](https://docs.google.com/spreadsheets/d/1LAbDFelKH7BlPRdnd2rvDT8RFhPa5SpCejlj-G8jREw/edit#gid=0) finished. The project passes level 1 but has a long way ahead for level 2.
The current state serves as a good level for publishing, and gives users a nice way to view the code.
The next step should be to allow users "the public" to be able to use the library without delving deep into the code.
The project provides an example website with both client, and server implementation, but still need the user to read the example code to understand how to use the project.
Starting from a new documentation should be a good step to make this project usable by others.
closes https://github.com/c4dt/TODO/issues/373
> data: adds APIR project maturity evaluation

- data.py
- data/IVRL/projects.yaml
- data/LAMP/projects.yaml
- data/LAP/projects.yaml
- data/LARA/projects.yaml
- data/LASEC/projects.yaml
- data/LIA/projects.yaml
- data/LIONS/projects.yaml
- data/MLO/projects.yaml
- data/RS3LAB/projects.yaml
- data/SACS/projects.yaml
- data/SPRING/projects.yaml
- data/SalatheLab/projects.yaml
- data/VLSC/projects.yaml
- requirements.txt
- test_app.py
closes https://github.com/c4dt/showcase/issues/307
This PR makes the field "type" required, and adds it to all existing projects. 
Each commit can be reviewed separately.
> feat: makes type a required field in projects

- data/C4DT/projects.yaml
- data/labs.yaml
WIP  but feel free to take a look and advice on the matter.
> data: adds c4dt and e-id demo

- views/products/app/freegaen.tpl
- views/products/app/spindle.tpl
- views/products/demo/calypso.tpl
- views/products/demo/drynx.tpl
- views/products/demo/medco.tpl
- views/products/demo/odyssey.tpl
- views/products/demo/omniledger.tpl
- views/products/demo/spindle.tpl
- views/products/demo/stainless-for-smart-contracts.tpl
- views/products/hands-on/calypso.tpl
- views/products/pilot/omniledger.tpl
Unified the way `retired` and `archived` projects are presented.
> Added and updated archive notices to app, demos, hands-on, and pilots

- data/COMPSEC/projects.yaml
add arkworks maturity evaluation
> data: add maturity evaluation arkworks

- data/LARA/projects.yaml
- devbox.lock
- views/products/presentation/stainless-for-smart-contracts.tpl
Some updates to the LARA projects.
> Update projects according to request from PhD student
